# Generated by Django 4.1.2 on 2022-10-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_recipe_ingrdients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingrdients',
            new_name='ingredients',
        ),
    ]
