---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # - name: Test
      #   run: docker compose run --rm app sh -c "python manage.py test"
      - name: PyTest
        run: docker compose run --rm app sh -c "pytest -p no:cacheprovider"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
        