---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test
        run: docker compose run --rm app sh -c "cd app && python manage.py wait_for_db && python manage.py test"
      - name: PyTest
        run: docker compose run --rm app sh -c "cd app && python manage.py wait_for_db && pytest -p no:cacheprovider"
      # - name: Lint
      #   run: docker compose run --rm app sh -c "flake8"
        